let posts = [
    {
        id: 1,
        username: "nadeem Ali",
        location: "Gojal",
        imageUrl: "images/img-1.jpg",
        likes: 5,
        isLike: false,
        view: 23,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "Benefits of reading : Smart, Diligent, Happy",
        comments: {
            userId: 2,
            text: "I like you",
            username: "haider",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    {
        id: 2,
        username: "nora-Khan",
        location: "Nagar",
        imageUrl: "images/img-2.jpg",
        likes: 10,
        isLike: false,
        view: 3,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "What books you should read in 2022?",
        comments: {
            userId: 2,
            text: "I like you",
            username: "shahzad",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    {
        id: 3,
        username: "shafi Khan",
        location: "Hunza",
        imageUrl: "images/img-3.jpg",
        likes: 3,
        isLike: false,
        view: 13,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "Why reading is Important for our children",
        comments: {
            userId: 2,
            text: "I like you",
            username: "shahzad",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    {
        id: 4,
        username: "nadeem Ali",
        location: "Gojal",
        imageUrl: "images/img-4.jpg",
        likes: 5,
        isLike: false,
        view: 23,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "Benefits of reading : Smart, Diligent, Happy",
        comments: {
            userId: 2,
            text: "I like you",
            username: "haider",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    {
        id: 5,
        username: "nora-Khan",
        location: "Nagar",
        imageUrl: "images/img-5.jpg",
        likes: 10,
        isLike: false,
        view: 3,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "What books you should read in 2022?",
        comments: {
            userId: 2,
            text: "I like you",
            username: "shahzad",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    {
        id: 6,
        username: "shafi Khan",
        location: "Hunza",
        imageUrl: "images/img-6.jpg",
        likes: 3,
        isLike: false,
        view: 13,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "Why reading is Important for our children",
        comments: {
            userId: 2,
            text: "I like you",
            username: "shahzad",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    // 
    {
        id: 7,
        username: "nadeem Ali",
        location: "Gojal",
        imageUrl: "images/img-7.jpg",
        likes: 5,
        isLike: false,
        view: 23,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "Benefits of reading : Smart, Diligent, Happy",
        comments: {
            userId: 2,
            text: "I like you",
            username: "haider",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    {
        id: 8,
        username: "nora-Khan",
        location: "Nagar",
        imageUrl: "images/img-8.jpg",
        likes: 10,
        isLike: false,
        view: 3,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "What books you should read in 2022?",
        comments: {
            userId: 2,
            text: "I like you",
            username: "shahzad",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    {
        id: 9,
        username: "shafi Khan",
        location: "Hunza",
        imageUrl: "images/img-9.jpg",
        likes: 3,
        isLike: false,
        view: 13,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "Why reading is Important for our children",
        comments: {
            userId: 2,
            text: "I like you",
            username: "shahzad",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    {
        id: 10,
        username: "nadeem Ali",
        location: "Gojal",
        imageUrl: "images/img-1.jpg",
        likes: 5,
        isLike: false,
        view: 23,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "Benefits of reading : Smart, Diligent, Happy",
        comments: {
            userId: 2,
            text: "I like you",
            username: "haider",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    {
        id: 11,
        username: "nora-Khan",
        location: "Nagar",
        imageUrl: "images/img-2.jpg",
        likes: 10,
        isLike: false,
        view: 3,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "What books you should read in 2022?",
        comments: {
            userId: 2,
            text: "I like you",
            username: "shahzad",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    {
        id: 12,
        username: "shafi Khan",
        location: "Hunza",
        imageUrl: "images/img-3.jpg",
        likes: 3,
        isLike: false,
        view: 13,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "Why reading is Important for our children",
        comments: {
            userId: 2,
            text: "I like you",
            username: "shahzad",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    {
        id: 13,
        username: "shafi Khan",
        location: "Hunza",
        imageUrl: "images/img-3.jpg",
        likes: 3,
        isLike: false,
        view: 13,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "Why reading is Important for our children",
        comments: {
            userId: 2,
            text: "I like you",
            username: "shahzad",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    {
        id: 14,
        username: "shafi Khan",
        location: "Hunza",
        imageUrl: "images/img-3.jpg",
        likes: 3,
        isLike: false,
        view: 13,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "Why reading is Important for our children",
        comments: {
            userId: 2,
            text: "I like you",
            username: "shahzad",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
    {
        id: 15,
        username: "shafi Khan",
        location: "Hunza",
        imageUrl: "images/img-3.jpg",
        likes: 3,
        isLike: false,
        view: 13,
        caption: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod, adipisci!",
        title: "Why reading is Important for our children",
        comments: {
            userId: 2,
            text: "I like you",
            username: "shahzad",
            likes: 0,
            createdAt: new Date(),
            updatedAd: new Date(),
        },
        createdAt: new Date("4 mints"),
        updatedAt: new Date(),
    },
]

export default posts